// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: melody qr code atd35

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_asset_93_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conS1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_conS1);
    lv_obj_set_width(ui_conS1, lv_pct(100));
    lv_obj_set_height(ui_conS1, lv_pct(100));
    lv_obj_set_align(ui_conS1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_conS1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_conS1);
    lv_img_set_src(ui_Image1, &ui_img_asset_83_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Image1, &ui_img_asset_93_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_conS1);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, lv_pct(100));
    lv_obj_set_height(ui_Container3, lv_pct(15));
    lv_obj_set_align(ui_Container3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Container3, &ui_img_asset_94_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icon_wifi = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_icon_wifi, 40);
    lv_obj_set_height(ui_icon_wifi, 40);
    lv_obj_set_x(ui_icon_wifi, 20);
    lv_obj_set_y(ui_icon_wifi, 0);
    lv_obj_set_align(ui_icon_wifi, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_icon_wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_icon_wifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_icon_wifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_icon_wifi, &ui_img_asset_73_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_icon_wifi, lv_color_hex(0xF8F8FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_icon_wifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_icon_wifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_icon_wifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_icon_wifi, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_icon_wifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_icon_wifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icon_mqtt = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_icon_mqtt, 40);
    lv_obj_set_height(ui_icon_mqtt, 40);
    lv_obj_set_x(ui_icon_mqtt, 60);
    lv_obj_set_y(ui_icon_mqtt, 0);
    lv_obj_set_align(ui_icon_mqtt, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_icon_mqtt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_icon_mqtt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_icon_mqtt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_icon_mqtt, &ui_img_asset_72_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_icon_mqtt, lv_color_hex(0xF8F8FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_icon_mqtt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_icon_mqtt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_icon_mqtt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_icon_mqtt, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_icon_mqtt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_icon_mqtt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_datetime = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_lb_datetime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_datetime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lb_datetime, -20);
    lv_obj_set_y(ui_lb_datetime, 0);
    lv_obj_set_align(ui_lb_datetime, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lb_datetime, "00:00:00");
    lv_obj_set_style_text_color(ui_lb_datetime, lv_color_hex(0xFCFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_datetime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_wifi_setting = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_btn_wifi_setting, 100);
    lv_obj_set_height(ui_btn_wifi_setting, lv_pct(90));
    lv_obj_set_align(ui_btn_wifi_setting, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_btn_wifi_setting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_wifi_setting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_wifi_setting, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_wifi_setting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_wifi_setting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_pass = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_btn_pass, 100);
    lv_obj_set_height(ui_btn_pass, lv_pct(90));
    lv_obj_set_x(ui_btn_pass, -10);
    lv_obj_set_y(ui_btn_pass, 0);
    lv_obj_set_align(ui_btn_pass, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_btn_pass, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_pass, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_pass, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_pass, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_pass, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_con_login = lv_obj_create(ui_conS1);
    lv_obj_remove_style_all(ui_con_login);
    lv_obj_set_width(ui_con_login, lv_pct(100));
    lv_obj_set_height(ui_con_login, lv_pct(80));
    lv_obj_set_x(ui_con_login, 0);
    lv_obj_set_y(ui_con_login, lv_pct(20));
    lv_obj_set_align(ui_con_login, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_con_login, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btn_login = lv_btn_create(ui_con_login);
    lv_obj_set_width(ui_btn_login, lv_pct(80));
    lv_obj_set_height(ui_btn_login, lv_pct(80));
    lv_obj_set_x(ui_btn_login, 0);
    lv_obj_set_y(ui_btn_login, -5);
    lv_obj_set_align(ui_btn_login, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_btn_login, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_login, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_login, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_login, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_login, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_con_login);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_height(ui_Container2, 60);
    lv_obj_set_width(ui_Container2, lv_pct(100));
    lv_obj_set_y(ui_Container2, 78);
    lv_obj_set_x(ui_Container2, lv_pct(0));
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_con_login);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, 70);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1,
                      "กรุณาแตะหน้าจอ เพื่อเข้าสู่ระบบ");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x1B0A78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Supermarket18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_con_login);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 90);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Please Touch");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x1B0A78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_con_key = lv_obj_create(ui_conS1);
    lv_obj_remove_style_all(ui_con_key);
    lv_obj_set_width(ui_con_key, lv_pct(100));
    lv_obj_set_height(ui_con_key, lv_pct(85));
    lv_obj_set_align(ui_con_key, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_con_key, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_con_key, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_con_key, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_con_key, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_check_key = lv_btn_create(ui_con_key);
    lv_obj_set_height(ui_btn_check_key, 40);
    lv_obj_set_width(ui_btn_check_key, lv_pct(90));
    lv_obj_set_x(ui_btn_check_key, 0);
    lv_obj_set_y(ui_btn_check_key, -30);
    lv_obj_set_align(ui_btn_check_key, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btn_check_key, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_check_key, lv_color_hex(0x14176B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_check_key, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_btn_command = lv_label_create(ui_btn_check_key);
    lv_obj_set_width(ui_lb_btn_command, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_btn_command, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lb_btn_command, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_btn_command, "Ok");
    lv_obj_set_style_text_font(ui_lb_btn_command, &ui_font_Supermarket18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tx_pin = lv_textarea_create(ui_con_key);
    lv_obj_set_width(ui_tx_pin, lv_pct(90));
    lv_obj_set_height(ui_tx_pin, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_tx_pin, 0);
    lv_obj_set_y(ui_tx_pin, -80);
    lv_obj_set_align(ui_tx_pin, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_tx_pin, "Placeholder...");
    lv_textarea_set_one_line(ui_tx_pin, true);
    lv_obj_set_style_radius(ui_tx_pin, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_tx_pin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_tx_pin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_tx_pin, 50, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Keyboard = lv_keyboard_create(ui_con_key);
    lv_keyboard_set_mode(ui_Keyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard, lv_pct(90));
    lv_obj_set_height(ui_Keyboard, lv_pct(50));
    lv_obj_set_x(ui_Keyboard, 0);
    lv_obj_set_y(ui_Keyboard, 18);
    lv_obj_set_align(ui_Keyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_Keyboard, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Keyboard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Keyboard, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Keyboard, 15, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_con_command = lv_obj_create(ui_conS1);
    lv_obj_remove_style_all(ui_con_command);
    lv_obj_set_width(ui_con_command, lv_pct(100));
    lv_obj_set_height(ui_con_command, lv_pct(85));
    lv_obj_set_align(ui_con_command, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_con_command, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_con_command, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_con_command, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_con_command, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container20 = lv_obj_create(ui_con_command);
    lv_obj_remove_style_all(ui_Container20);
    lv_obj_set_width(ui_Container20, lv_pct(100));
    lv_obj_set_height(ui_Container20, lv_pct(30));
    lv_obj_set_align(ui_Container20, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btn_ldr = lv_btn_create(ui_Container20);
    lv_obj_set_width(ui_btn_ldr, 73);
    lv_obj_set_height(ui_btn_ldr, 30);
    lv_obj_set_x(ui_btn_ldr, -5);
    lv_obj_set_y(ui_btn_ldr, -15);
    lv_obj_set_align(ui_btn_ldr, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_btn_ldr, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_ldr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_ldr, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_ldr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_ldr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_ldr = lv_label_create(ui_btn_ldr);
    lv_obj_set_width(ui_lb_ldr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_ldr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lb_ldr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_ldr, "ldr : 1 : 1500");
    lv_obj_set_style_text_color(ui_lb_ldr, lv_color_hex(0x1B0A78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_ldr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_ldr, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_slot = lv_btn_create(ui_Container20);
    lv_obj_set_width(ui_btn_slot, 55);
    lv_obj_set_height(ui_btn_slot, 30);
    lv_obj_set_x(ui_btn_slot, -5);
    lv_obj_set_y(ui_btn_slot, 10);
    lv_obj_set_align(ui_btn_slot, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_btn_slot, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_slot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_slot, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_slot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_slot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_slot = lv_label_create(ui_btn_slot);
    lv_obj_set_width(ui_lb_slot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_slot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lb_slot, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_slot, "slot : 41");
    lv_obj_set_style_text_color(ui_lb_slot, lv_color_hex(0x1B0A78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_slot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_slot, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_mode = lv_btn_create(ui_Container20);
    lv_obj_set_width(ui_btn_mode, 60);
    lv_obj_set_height(ui_btn_mode, 30);
    lv_obj_set_x(ui_btn_mode, -60);
    lv_obj_set_y(ui_btn_mode, 10);
    lv_obj_set_align(ui_btn_mode, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_btn_mode, lv_color_hex(0x3519C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_mode, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_mode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_mode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_mode = lv_label_create(ui_btn_mode);
    lv_obj_set_width(ui_lb_mode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_mode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lb_mode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_mode, "mode : 6");
    lv_obj_set_style_text_color(ui_lb_mode, lv_color_hex(0x1B0A78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_mode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_mode, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_command_home = lv_btn_create(ui_Container20);
    lv_obj_set_width(ui_btn_command_home, 50);
    lv_obj_set_height(ui_btn_command_home, 50);
    lv_obj_set_x(ui_btn_command_home, 10);
    lv_obj_set_y(ui_btn_command_home, 0);
    lv_obj_set_align(ui_btn_command_home, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_btn_command_home, lv_color_hex(0x2225B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_command_home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_command_home, &ui_img_asset_91_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn_command_home, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn_command_home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_command_home, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_command_home, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_command_home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_setting = lv_btn_create(ui_Container20);
    lv_obj_set_height(ui_btn_setting, 30);
    lv_obj_set_width(ui_btn_setting, lv_pct(35));
    lv_obj_set_x(ui_btn_setting, 10);
    lv_obj_set_y(ui_btn_setting, 0);
    lv_obj_set_align(ui_btn_setting, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_btn_setting, lv_color_hex(0x3519C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_setting = lv_label_create(ui_btn_setting);
    lv_obj_set_width(ui_lb_setting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_setting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lb_setting, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_setting, "ตั้งค่า : 65M000000");
    lv_obj_set_style_text_color(ui_lb_setting, lv_color_hex(0xFCFCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_setting, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_change_pass = lv_btn_create(ui_Container20);
    lv_obj_set_height(ui_btn_change_pass, 30);
    lv_obj_set_width(ui_btn_change_pass, lv_pct(15));
    lv_obj_set_x(ui_btn_change_pass, 75);
    lv_obj_set_y(ui_btn_change_pass, 0);
    lv_obj_set_align(ui_btn_change_pass, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_btn_change_pass, lv_color_hex(0x3519C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_change_pass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_change_pass = lv_label_create(ui_btn_change_pass);
    lv_obj_set_width(ui_lb_change_pass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_change_pass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lb_change_pass, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_change_pass, "เปลี่ยนรหัส");
    lv_obj_set_style_text_color(ui_lb_change_pass, lv_color_hex(0xFCFCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_change_pass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_change_pass, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container22 = lv_obj_create(ui_con_command);
    lv_obj_remove_style_all(ui_Container22);
    lv_obj_set_width(ui_Container22, lv_pct(100));
    lv_obj_set_height(ui_Container22, lv_pct(30));
    lv_obj_set_x(ui_Container22, 0);
    lv_obj_set_y(ui_Container22, lv_pct(30));
    lv_obj_set_align(ui_Container22, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container22, lv_color_hex(0x3519C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_power = lv_btn_create(ui_Container22);
    lv_obj_set_width(ui_btn_power, 50);
    lv_obj_set_height(ui_btn_power, 50);
    lv_obj_set_y(ui_btn_power, 0);
    lv_obj_set_x(ui_btn_power, lv_pct(-30));
    lv_obj_set_align(ui_btn_power, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_btn_power, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_power, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_power, &ui_img_asset_97_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_power, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_power, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_power, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_jok = lv_btn_create(ui_Container22);
    lv_obj_set_width(ui_btn_jok, 50);
    lv_obj_set_height(ui_btn_jok, 50);
    lv_obj_set_y(ui_btn_jok, 0);
    lv_obj_set_x(ui_btn_jok, lv_pct(-15));
    lv_obj_set_align(ui_btn_jok, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_btn_jok, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_jok, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_jok, &ui_img_asset_98_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_jok, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_jok, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_jok, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_start = lv_btn_create(ui_Container22);
    lv_obj_set_width(ui_btn_start, 50);
    lv_obj_set_height(ui_btn_start, 50);
    lv_obj_set_align(ui_btn_start, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_btn_start, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_start, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_start, &ui_img_asset_99_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_start, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_start, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_start, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_spin = lv_btn_create(ui_Container22);
    lv_obj_set_width(ui_btn_spin, 50);
    lv_obj_set_height(ui_btn_spin, 50);
    lv_obj_set_y(ui_btn_spin, 0);
    lv_obj_set_x(ui_btn_spin, lv_pct(15));
    lv_obj_set_align(ui_btn_spin, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_btn_spin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_spin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_spin, &ui_img_asset_100_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_spin, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_spin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_spin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_temp = lv_btn_create(ui_Container22);
    lv_obj_set_width(ui_btn_temp, 50);
    lv_obj_set_height(ui_btn_temp, 50);
    lv_obj_set_y(ui_btn_temp, 0);
    lv_obj_set_x(ui_btn_temp, lv_pct(30));
    lv_obj_set_align(ui_btn_temp, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_btn_temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_temp, &ui_img_asset_101_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_temp, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_temp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_con_program = lv_obj_create(ui_con_command);
    lv_obj_remove_style_all(ui_con_program);
    lv_obj_set_width(ui_con_program, lv_pct(100));
    lv_obj_set_height(ui_con_program, lv_pct(40));
    lv_obj_set_align(ui_con_program, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_con_program, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_con_program, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_con_program, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_program1 = lv_btn_create(ui_con_program);
    lv_obj_set_height(ui_btn_program1, 30);
    lv_obj_set_width(ui_btn_program1, lv_pct(25));
    lv_obj_set_x(ui_btn_program1, lv_pct(8));
    lv_obj_set_y(ui_btn_program1, lv_pct(-25));
    lv_obj_set_align(ui_btn_program1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_btn_program1, lv_color_hex(0x3519C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_program1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_program1 = lv_label_create(ui_btn_program1);
    lv_obj_set_width(ui_lb_program1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_program1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lb_program1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_program1, "ซักน้ำเย็น");
    lv_obj_set_style_text_color(ui_lb_program1, lv_color_hex(0xFCFCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_program1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_program1, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_program2 = lv_btn_create(ui_con_program);
    lv_obj_set_height(ui_btn_program2, 30);
    lv_obj_set_width(ui_btn_program2, lv_pct(25));
    lv_obj_set_x(ui_btn_program2, lv_pct(0));
    lv_obj_set_y(ui_btn_program2, lv_pct(-25));
    lv_obj_set_align(ui_btn_program2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_btn_program2, lv_color_hex(0x3519C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_program2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_program2 = lv_label_create(ui_btn_program2);
    lv_obj_set_width(ui_lb_program2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_program2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lb_program2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_program2, "ซักน้ำอุ่น");
    lv_obj_set_style_text_color(ui_lb_program2, lv_color_hex(0xFCFCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_program2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_program2, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_program3 = lv_btn_create(ui_con_program);
    lv_obj_set_height(ui_btn_program3, 30);
    lv_obj_set_width(ui_btn_program3, lv_pct(25));
    lv_obj_set_x(ui_btn_program3, lv_pct(-8));
    lv_obj_set_y(ui_btn_program3, lv_pct(-25));
    lv_obj_set_align(ui_btn_program3, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_btn_program3, lv_color_hex(0x3519C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_program3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_program3 = lv_label_create(ui_btn_program3);
    lv_obj_set_width(ui_lb_program3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_program3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lb_program3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_program3, "ซักน้ำร้อน");
    lv_obj_set_style_text_color(ui_lb_program3, lv_color_hex(0xFCFCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_program3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_program3, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_program5 = lv_btn_create(ui_con_program);
    lv_obj_set_height(ui_btn_program5, 30);
    lv_obj_set_width(ui_btn_program5, lv_pct(25));
    lv_obj_set_x(ui_btn_program5, lv_pct(8));
    lv_obj_set_y(ui_btn_program5, lv_pct(15));
    lv_obj_set_align(ui_btn_program5, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_btn_program5, lv_color_hex(0x3519C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_program5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_program5 = lv_label_create(ui_btn_program5);
    lv_obj_set_width(ui_lb_program5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_program5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lb_program5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_program5, "ล้าง+ปั่น");
    lv_obj_set_style_text_color(ui_lb_program5, lv_color_hex(0xFCFCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_program5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_program5, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_program6 = lv_btn_create(ui_con_program);
    lv_obj_set_height(ui_btn_program6, 30);
    lv_obj_set_width(ui_btn_program6, lv_pct(25));
    lv_obj_set_x(ui_btn_program6, lv_pct(0));
    lv_obj_set_y(ui_btn_program6, lv_pct(15));
    lv_obj_set_align(ui_btn_program6, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_btn_program6, lv_color_hex(0x3519C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_program6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_program6 = lv_label_create(ui_btn_program6);
    lv_obj_set_width(ui_lb_program6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_program6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lb_program6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_program6, "ปั่น");
    lv_obj_set_style_text_color(ui_lb_program6, lv_color_hex(0xFCFCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_program6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_program6, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_program4 = lv_btn_create(ui_con_program);
    lv_obj_set_height(ui_btn_program4, 30);
    lv_obj_set_width(ui_btn_program4, lv_pct(25));
    lv_obj_set_x(ui_btn_program4, lv_pct(-8));
    lv_obj_set_y(ui_btn_program4, lv_pct(15));
    lv_obj_set_align(ui_btn_program4, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_btn_program4, lv_color_hex(0x3519C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_program4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_program4 = lv_label_create(ui_btn_program4);
    lv_obj_set_width(ui_lb_program4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_program4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lb_program4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_program4, "ล้างถังซัก");
    lv_obj_set_style_text_color(ui_lb_program4, lv_color_hex(0xFCFCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_program4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_program4, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_con_wifi = lv_obj_create(ui_conS1);
    lv_obj_remove_style_all(ui_con_wifi);
    lv_obj_set_width(ui_con_wifi, lv_pct(100));
    lv_obj_set_height(ui_con_wifi, lv_pct(85));
    lv_obj_set_align(ui_con_wifi, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_con_wifi, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_con_wifi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_con_wifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_con_wifi, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_save_wifi = lv_btn_create(ui_con_wifi);
    lv_obj_set_height(ui_btn_save_wifi, 40);
    lv_obj_set_width(ui_btn_save_wifi, lv_pct(90));
    lv_obj_set_align(ui_btn_save_wifi, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btn_save_wifi, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_save_wifi, lv_color_hex(0x14176B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_save_wifi, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_btn_command2 = lv_label_create(ui_btn_save_wifi);
    lv_obj_set_width(ui_lb_btn_command2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_btn_command2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lb_btn_command2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_btn_command2, "Ok");
    lv_obj_set_style_text_font(ui_lb_btn_command2, &ui_font_Supermarket18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tx_wifi_name = lv_textarea_create(ui_con_wifi);
    lv_obj_set_width(ui_tx_wifi_name, lv_pct(90));
    lv_obj_set_height(ui_tx_wifi_name, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_tx_wifi_name, 0);
    lv_obj_set_y(ui_tx_wifi_name, 10);
    lv_obj_set_align(ui_tx_wifi_name, LV_ALIGN_TOP_MID);
    lv_textarea_set_placeholder_text(ui_tx_wifi_name, "wifi name");
    lv_textarea_set_one_line(ui_tx_wifi_name, true);
    lv_obj_set_style_radius(ui_tx_wifi_name, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_tx_wifi_name, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_tx_wifi_name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_tx_wifi_name, 50, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_tx_wifi_pass = lv_textarea_create(ui_con_wifi);
    lv_obj_set_width(ui_tx_wifi_pass, lv_pct(90));
    lv_obj_set_height(ui_tx_wifi_pass, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_tx_wifi_pass, 0);
    lv_obj_set_y(ui_tx_wifi_pass, 60);
    lv_obj_set_align(ui_tx_wifi_pass, LV_ALIGN_TOP_MID);
    lv_textarea_set_placeholder_text(ui_tx_wifi_pass, "wifi pass");
    lv_textarea_set_one_line(ui_tx_wifi_pass, true);
    lv_textarea_set_password_mode(ui_tx_wifi_pass, true);
    lv_obj_set_style_radius(ui_tx_wifi_pass, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_tx_wifi_pass, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_tx_wifi_pass, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_tx_wifi_pass, 50, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Keyboard2 = lv_keyboard_create(ui_con_wifi);
    lv_obj_set_width(ui_Keyboard2, lv_pct(90));
    lv_obj_set_height(ui_Keyboard2, lv_pct(50));
    lv_obj_set_x(ui_Keyboard2, 0);
    lv_obj_set_y(ui_Keyboard2, -20);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_Keyboard2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Keyboard2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Keyboard2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Keyboard2, 15, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_con_all_setting = lv_obj_create(ui_conS1);
    lv_obj_remove_style_all(ui_con_all_setting);
    lv_obj_set_width(ui_con_all_setting, lv_pct(100));
    lv_obj_set_height(ui_con_all_setting, lv_pct(85));
    lv_obj_set_align(ui_con_all_setting, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_con_all_setting, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_con_all_setting, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_con_all_setting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_con_all_setting, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_con_all_setting);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, lv_pct(100));
    lv_obj_set_height(ui_Container4, lv_pct(40));
    lv_obj_set_x(ui_Container4, 0);
    lv_obj_set_y(ui_Container4, 20);
    lv_obj_set_align(ui_Container4, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container4, lv_color_hex(0x3519C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_display_setting = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_lb_display_setting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_display_setting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lb_display_setting, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_display_setting, "ตั้งค่า");
    lv_obj_set_style_text_color(ui_lb_display_setting, lv_color_hex(0xFDFDFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_display_setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_display_setting, &ui_font_Supermarket48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_back = lv_btn_create(ui_con_all_setting);
    lv_obj_set_height(ui_btn_back, 40);
    lv_obj_set_width(ui_btn_back, lv_pct(15));
    lv_obj_set_y(ui_btn_back, 40);
    lv_obj_set_x(ui_btn_back, lv_pct(4));
    lv_obj_set_align(ui_btn_back, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_btn_back, lv_color_hex(0x3519C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_btn_back);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Back");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFDFDFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_Supermarket18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_Reset = lv_btn_create(ui_con_all_setting);
    lv_obj_set_height(ui_btn_Reset, 40);
    lv_obj_set_width(ui_btn_Reset, lv_pct(15));
    lv_obj_set_y(ui_btn_Reset, 40);
    lv_obj_set_x(ui_btn_Reset, lv_pct(-4));
    lv_obj_set_align(ui_btn_Reset, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_btn_Reset, lv_color_hex(0x3519C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_Reset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_btn_Reset);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Reset");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFDFDFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_Supermarket18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_Up = lv_btn_create(ui_con_all_setting);
    lv_obj_set_height(ui_btn_Up, 40);
    lv_obj_set_width(ui_btn_Up, lv_pct(15));
    lv_obj_set_y(ui_btn_Up, 40);
    lv_obj_set_x(ui_btn_Up, lv_pct(0));
    lv_obj_set_align(ui_btn_Up, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_btn_Up, lv_color_hex(0x3519C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_Up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_btn_Up);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Up");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xFDFDFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &ui_font_Supermarket18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_Down = lv_btn_create(ui_con_all_setting);
    lv_obj_set_height(ui_btn_Down, 40);
    lv_obj_set_width(ui_btn_Down, lv_pct(15));
    lv_obj_set_y(ui_btn_Down, 40);
    lv_obj_set_x(ui_btn_Down, lv_pct(23));
    lv_obj_set_align(ui_btn_Down, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_btn_Down, lv_color_hex(0x3519C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_Down, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_btn_Down);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Down");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFDFDFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_Supermarket18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_Setting = lv_btn_create(ui_con_all_setting);
    lv_obj_set_height(ui_btn_Setting, 40);
    lv_obj_set_width(ui_btn_Setting, lv_pct(15));
    lv_obj_set_y(ui_btn_Setting, 40);
    lv_obj_set_x(ui_btn_Setting, lv_pct(-23));
    lv_obj_set_align(ui_btn_Setting, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_btn_Setting, lv_color_hex(0x3519C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_Setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_btn_Setting);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Setting");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xFDFDFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &ui_font_Supermarket18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conS2 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_conS2);
    lv_obj_set_width(ui_conS2, lv_pct(100));
    lv_obj_set_height(ui_conS2, lv_pct(100));
    lv_obj_set_align(ui_conS2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_conS2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_conS2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_conS2);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, lv_pct(100));
    lv_obj_set_height(ui_Container1, lv_pct(30));
    lv_obj_set_align(ui_Container1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btn_back1 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_btn_back1, lv_pct(15));
    lv_obj_set_height(ui_btn_back1, lv_pct(80));
    lv_obj_set_x(ui_btn_back1, 10);
    lv_obj_set_y(ui_btn_back1, 0);
    lv_obj_set_align(ui_btn_back1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_btn_back1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_back1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_back1, &ui_img_asset_84_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_back1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_back1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_back1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, -10);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "กรุณาเลือกรูปแบบการซัก");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x1B0A78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Supermarket18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, 10);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Please choose a washing mode.");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x1B0A78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_con_shoot = lv_obj_create(ui_conS2);
    lv_obj_remove_style_all(ui_con_shoot);
    lv_obj_set_width(ui_con_shoot, lv_pct(100));
    lv_obj_set_height(ui_con_shoot, lv_pct(55));
    lv_obj_set_x(ui_con_shoot, 0);
    lv_obj_set_y(ui_con_shoot, lv_pct(30));
    lv_obj_set_align(ui_con_shoot, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_con_shoot, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_con_shoot, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pn_mode1 = lv_obj_create(ui_con_shoot);
    lv_obj_set_width(ui_pn_mode1, 130);
    lv_obj_set_height(ui_pn_mode1, 150);
    lv_obj_set_y(ui_pn_mode1, 0);
    lv_obj_set_x(ui_pn_mode1, lv_pct(5));
    lv_obj_set_align(ui_pn_mode1, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_pn_mode1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pn_mode1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pn_mode1, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pn_mode1, lv_color_hex(0x072798), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pn_mode1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pn_mode1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pn_mode1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_price1 = lv_label_create(ui_pn_mode1);
    lv_obj_set_width(ui_price1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_price1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_price1, 0);
    lv_obj_set_y(ui_price1, 30);
    lv_obj_set_align(ui_price1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_price1, "30.-");
    lv_obj_set_style_text_color(ui_price1, lv_color_hex(0x433F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_price1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_price1, &ui_font_Supermarket48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image12 = lv_img_create(ui_pn_mode1);
    lv_img_set_src(ui_Image12, &ui_img_asset_87_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image12, 0);
    lv_obj_set_y(ui_Image12, -5);
    lv_obj_set_align(ui_Image12, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pn_mode3 = lv_obj_create(ui_con_shoot);
    lv_obj_set_width(ui_pn_mode3, 130);
    lv_obj_set_height(ui_pn_mode3, 150);
    lv_obj_set_y(ui_pn_mode3, 0);
    lv_obj_set_x(ui_pn_mode3, lv_pct(-5));
    lv_obj_set_align(ui_pn_mode3, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_pn_mode3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pn_mode3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pn_mode3, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pn_mode3, lv_color_hex(0x072798), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pn_mode3, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pn_mode3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pn_mode3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_price3 = lv_label_create(ui_pn_mode3);
    lv_obj_set_width(ui_price3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_price3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_price3, 0);
    lv_obj_set_y(ui_price3, 30);
    lv_obj_set_align(ui_price3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_price3, "30.-");
    lv_obj_set_style_text_color(ui_price3, lv_color_hex(0x433F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_price3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_price3, &ui_font_Supermarket48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image13 = lv_img_create(ui_pn_mode3);
    lv_img_set_src(ui_Image13, &ui_img_asset_89_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image13, 0);
    lv_obj_set_y(ui_Image13, -5);
    lv_obj_set_align(ui_Image13, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pn_mode2 = lv_obj_create(ui_con_shoot);
    lv_obj_set_width(ui_pn_mode2, 130);
    lv_obj_set_height(ui_pn_mode2, 150);
    lv_obj_set_align(ui_pn_mode2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pn_mode2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pn_mode2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pn_mode2, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pn_mode2, lv_color_hex(0x072798), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pn_mode2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pn_mode2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pn_mode2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_price2 = lv_label_create(ui_pn_mode2);
    lv_obj_set_width(ui_price2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_price2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_price2, 0);
    lv_obj_set_y(ui_price2, 30);
    lv_obj_set_align(ui_price2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_price2, "30.-");
    lv_obj_set_style_text_color(ui_price2, lv_color_hex(0x433F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_price2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_price2, &ui_font_Supermarket48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image11 = lv_img_create(ui_pn_mode2);
    lv_img_set_src(ui_Image11, &ui_img_asset_88_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image11, 0);
    lv_obj_set_y(ui_Image11, -5);
    lv_obj_set_align(ui_Image11, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_con_shoot1 = lv_obj_create(ui_conS2);
    lv_obj_remove_style_all(ui_con_shoot1);
    lv_obj_set_width(ui_con_shoot1, lv_pct(100));
    lv_obj_set_height(ui_con_shoot1, lv_pct(55));
    lv_obj_set_x(ui_con_shoot1, 0);
    lv_obj_set_y(ui_con_shoot1, lv_pct(30));
    lv_obj_set_align(ui_con_shoot1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_con_shoot1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_con_shoot1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pn_dry1 = lv_obj_create(ui_con_shoot1);
    lv_obj_set_width(ui_pn_dry1, 130);
    lv_obj_set_height(ui_pn_dry1, 150);
    lv_obj_set_y(ui_pn_dry1, 0);
    lv_obj_set_x(ui_pn_dry1, lv_pct(5));
    lv_obj_set_align(ui_pn_dry1, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_pn_dry1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pn_dry1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pn_dry1, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pn_dry1, lv_color_hex(0x072798), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pn_dry1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pn_dry1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pn_dry1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_price_dry1 = lv_label_create(ui_pn_dry1);
    lv_obj_set_width(ui_price_dry1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_price_dry1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_price_dry1, 0);
    lv_obj_set_y(ui_price_dry1, 30);
    lv_obj_set_align(ui_price_dry1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_price_dry1, "40.-");
    lv_obj_set_style_text_color(ui_price_dry1, lv_color_hex(0x433F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_price_dry1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_price_dry1, &ui_font_Supermarket48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_pn_dry1);
    lv_img_set_src(ui_Image7, &ui_img_asset_96_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, 0);
    lv_obj_set_y(ui_Image7, -5);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_con_time_dry = lv_obj_create(ui_pn_dry1);
    lv_obj_remove_style_all(ui_con_time_dry);
    lv_obj_set_width(ui_con_time_dry, 80);
    lv_obj_set_height(ui_con_time_dry, 50);
    lv_obj_set_x(ui_con_time_dry, 20);
    lv_obj_set_y(ui_con_time_dry, 0);
    lv_obj_set_align(ui_con_time_dry, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_con_time_dry, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lb_timedry1 = lv_label_create(ui_con_time_dry);
    lv_obj_set_width(ui_lb_timedry1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_timedry1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lb_timedry1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_timedry1, "40");
    lv_obj_set_style_text_color(ui_lb_timedry1, lv_color_hex(0x433F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_timedry1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_timedry1, &ui_font_Supermarket18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_con_time_dry);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 0);
    lv_obj_set_y(ui_Label18, 20);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "นาที (min.)");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0x433F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pn_dry2 = lv_obj_create(ui_con_shoot1);
    lv_obj_set_width(ui_pn_dry2, 130);
    lv_obj_set_height(ui_pn_dry2, 150);
    lv_obj_set_align(ui_pn_dry2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pn_dry2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pn_dry2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pn_dry2, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pn_dry2, lv_color_hex(0x072798), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pn_dry2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pn_dry2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pn_dry2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_price_dry2 = lv_label_create(ui_pn_dry2);
    lv_obj_set_width(ui_price_dry2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_price_dry2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_price_dry2, 0);
    lv_obj_set_y(ui_price_dry2, 30);
    lv_obj_set_align(ui_price_dry2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_price_dry2, "30.-");
    lv_obj_set_style_text_color(ui_price_dry2, lv_color_hex(0x433F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_price_dry2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_price_dry2, &ui_font_Supermarket48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_pn_dry2);
    lv_img_set_src(ui_Image8, &ui_img_asset_96_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, 0);
    lv_obj_set_y(ui_Image8, -5);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_con_time_dry3 = lv_obj_create(ui_pn_dry2);
    lv_obj_remove_style_all(ui_con_time_dry3);
    lv_obj_set_width(ui_con_time_dry3, 80);
    lv_obj_set_height(ui_con_time_dry3, 50);
    lv_obj_set_x(ui_con_time_dry3, 20);
    lv_obj_set_y(ui_con_time_dry3, 0);
    lv_obj_set_align(ui_con_time_dry3, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_con_time_dry3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lb_timedry2 = lv_label_create(ui_con_time_dry3);
    lv_obj_set_width(ui_lb_timedry2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_timedry2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lb_timedry2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_timedry2, "30");
    lv_obj_set_style_text_color(ui_lb_timedry2, lv_color_hex(0x433F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_timedry2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_timedry2, &ui_font_Supermarket18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_con_time_dry3);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 0);
    lv_obj_set_y(ui_Label22, 20);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "นาที (min.)");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0x433F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pn_dry3 = lv_obj_create(ui_con_shoot1);
    lv_obj_set_width(ui_pn_dry3, 130);
    lv_obj_set_height(ui_pn_dry3, 150);
    lv_obj_set_y(ui_pn_dry3, 0);
    lv_obj_set_x(ui_pn_dry3, lv_pct(-5));
    lv_obj_set_align(ui_pn_dry3, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_pn_dry3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pn_dry3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pn_dry3, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pn_dry3, lv_color_hex(0x072798), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pn_dry3, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pn_dry3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pn_dry3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_price_dry3 = lv_label_create(ui_pn_dry3);
    lv_obj_set_width(ui_price_dry3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_price_dry3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_price_dry3, 0);
    lv_obj_set_y(ui_price_dry3, 30);
    lv_obj_set_align(ui_price_dry3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_price_dry3, "50.-");
    lv_obj_set_style_text_color(ui_price_dry3, lv_color_hex(0x433F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_price_dry3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_price_dry3, &ui_font_Supermarket48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_img_create(ui_pn_dry3);
    lv_img_set_src(ui_Image9, &ui_img_asset_96_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image9, 0);
    lv_obj_set_y(ui_Image9, -5);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_con_time_dry2 = lv_obj_create(ui_pn_dry3);
    lv_obj_remove_style_all(ui_con_time_dry2);
    lv_obj_set_width(ui_con_time_dry2, 80);
    lv_obj_set_height(ui_con_time_dry2, 50);
    lv_obj_set_x(ui_con_time_dry2, 20);
    lv_obj_set_y(ui_con_time_dry2, 0);
    lv_obj_set_align(ui_con_time_dry2, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_con_time_dry2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lb_timedry3 = lv_label_create(ui_con_time_dry2);
    lv_obj_set_width(ui_lb_timedry3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_timedry3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lb_timedry3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_timedry3, "50");
    lv_obj_set_style_text_color(ui_lb_timedry3, lv_color_hex(0x433F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_timedry3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_timedry3, &ui_font_Supermarket18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_con_time_dry2);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 0);
    lv_obj_set_y(ui_Label15, 20);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "นาที (min.)");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x433F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conS3 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_conS3);
    lv_obj_set_width(ui_conS3, lv_pct(100));
    lv_obj_set_height(ui_conS3, lv_pct(100));
    lv_obj_set_align(ui_conS3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_conS3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_conS3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container6 = lv_obj_create(ui_conS3);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, lv_pct(100));
    lv_obj_set_height(ui_Container6, lv_pct(30));
    lv_obj_set_align(ui_Container6, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btn_back2 = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_btn_back2, lv_pct(15));
    lv_obj_set_height(ui_btn_back2, lv_pct(80));
    lv_obj_set_x(ui_btn_back2, 10);
    lv_obj_set_y(ui_btn_back2, 0);
    lv_obj_set_align(ui_btn_back2, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_btn_back2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_back2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_back2, &ui_img_asset_84_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_back2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_back2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_back2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, -10);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "กรุณาเลือกรูปแบบจ่ายเงิน");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x1B0A78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Supermarket18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, 10);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Please select a payment method.");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x1B0A78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_conS3);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, lv_pct(100));
    lv_obj_set_height(ui_Container7, lv_pct(55));
    lv_obj_set_x(ui_Container7, 0);
    lv_obj_set_y(ui_Container7, lv_pct(30));
    lv_obj_set_align(ui_Container7, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pn_qr = lv_obj_create(ui_Container7);
    lv_obj_set_width(ui_pn_qr, 130);
    lv_obj_set_height(ui_pn_qr, 150);
    lv_obj_set_x(ui_pn_qr, -80);
    lv_obj_set_y(ui_pn_qr, 0);
    lv_obj_set_align(ui_pn_qr, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_pn_qr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pn_qr, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pn_qr, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pn_qr, lv_color_hex(0x072798), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pn_qr, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pn_qr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pn_qr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_pn_qr);
    lv_img_set_src(ui_Image3, &ui_img_asset_86_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pn_coin = lv_obj_create(ui_Container7);
    lv_obj_set_width(ui_pn_coin, 130);
    lv_obj_set_height(ui_pn_coin, 150);
    lv_obj_set_x(ui_pn_coin, 80);
    lv_obj_set_y(ui_pn_coin, 0);
    lv_obj_set_align(ui_pn_coin, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_pn_coin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pn_coin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pn_coin, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pn_coin, lv_color_hex(0x072798), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pn_coin, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pn_coin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pn_coin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_pn_coin);
    lv_img_set_src(ui_Image2, &ui_img_asset_85_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_conS4 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_conS4);
    lv_obj_set_width(ui_conS4, lv_pct(100));
    lv_obj_set_height(ui_conS4, lv_pct(100));
    lv_obj_set_align(ui_conS4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_conS4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_conS4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container5 = lv_obj_create(ui_conS4);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, lv_pct(100));
    lv_obj_set_height(ui_Container5, lv_pct(30));
    lv_obj_set_align(ui_Container5, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btn_back3 = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_btn_back3, lv_pct(15));
    lv_obj_set_height(ui_btn_back3, lv_pct(80));
    lv_obj_set_x(ui_btn_back3, 10);
    lv_obj_set_y(ui_btn_back3, 0);
    lv_obj_set_align(ui_btn_back3, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_btn_back3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_back3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_back3, &ui_img_asset_84_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_back3, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_back3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_back3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, -10);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "กรุณาหยอดเหรียญให้ครบ");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x1B0A78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Supermarket18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 10);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Please insert the correct amount of coins.");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x1B0A78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_conS4);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, lv_pct(100));
    lv_obj_set_height(ui_Container8, lv_pct(55));
    lv_obj_set_x(ui_Container8, 0);
    lv_obj_set_y(ui_Container8, lv_pct(30));
    lv_obj_set_align(ui_Container8, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container8, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_coin = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_lb_coin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_coin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lb_coin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_coin, "30.-");
    lv_obj_set_style_text_color(ui_lb_coin, lv_color_hex(0x433F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_coin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_coin, &ui_font_Supermarget72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_Container8);
    lv_img_set_src(ui_Image4, &ui_img_asset_85_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, 50);
    lv_obj_set_y(ui_Image4, 0);
    lv_obj_set_align(ui_Image4, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_conS5 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_conS5);
    lv_obj_set_width(ui_conS5, lv_pct(100));
    lv_obj_set_height(ui_conS5, lv_pct(100));
    lv_obj_set_align(ui_conS5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_conS5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_conS5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container9 = lv_obj_create(ui_conS5);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, lv_pct(100));
    lv_obj_set_height(ui_Container9, lv_pct(28));
    lv_obj_set_align(ui_Container9, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btn_back4 = lv_btn_create(ui_Container9);
    lv_obj_set_width(ui_btn_back4, lv_pct(15));
    lv_obj_set_height(ui_btn_back4, lv_pct(80));
    lv_obj_set_x(ui_btn_back4, 10);
    lv_obj_set_y(ui_btn_back4, 0);
    lv_obj_set_align(ui_btn_back4, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_btn_back4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_back4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_back4, &ui_img_asset_84_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_back4, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_back4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_back4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_clock_qr = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_lb_clock_qr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_clock_qr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lb_clock_qr, 15);
    lv_obj_set_y(ui_lb_clock_qr, -15);
    lv_obj_set_align(ui_lb_clock_qr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_clock_qr, "00:00");
    lv_obj_set_style_text_color(ui_lb_clock_qr, lv_color_hex(0x433F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_clock_qr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_clock_qr, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_Container9);
    lv_img_set_src(ui_Image5, &ui_img_asset_92_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, -40);
    lv_obj_set_y(ui_Image5, 0);
    lv_obj_set_align(ui_Image5, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lb_promtpay = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_lb_promtpay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_promtpay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lb_promtpay, 170);
    lv_obj_set_y(ui_lb_promtpay, -15);
    lv_obj_set_align(ui_lb_promtpay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_promtpay, "พร้อมเพย์");
    lv_obj_set_style_text_color(ui_lb_promtpay, lv_color_hex(0x1B0A78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_promtpay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_promtpay, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_conS5);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, lv_pct(100));
    lv_obj_set_height(ui_Container10, lv_pct(63));
    lv_obj_set_x(ui_Container10, 0);
    lv_obj_set_y(ui_Container10, lv_pct(28));
    lv_obj_set_align(ui_Container10, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container11 = lv_obj_create(ui_Container10);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_height(ui_Container11, 180);
    lv_obj_set_width(ui_Container11, lv_pct(100));
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container11, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 45);
    lv_obj_set_y(ui_Label8, 45);
    lv_label_set_text(ui_Label8, "Please scan the QR code.");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x1B0A78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 45);
    lv_obj_set_y(ui_Label11, 20);
    lv_label_set_text(ui_Label11, "กรุณาแสกนคิวอาร์โค้ด");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x1B0A78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_Supermarket18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_price_qr = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_lb_price_qr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_price_qr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_lb_price_qr, -30);
    lv_obj_set_x(ui_lb_price_qr, lv_pct(13));
    lv_obj_set_align(ui_lb_price_qr, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_lb_price_qr, "30.-");
    lv_obj_set_style_text_color(ui_lb_price_qr, lv_color_hex(0x433F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_price_qr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_price_qr, &ui_font_Supermarget72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_qr_frame = lv_obj_create(ui_Container10);
    lv_obj_set_width(ui_qr_frame, lv_pct(42));
    lv_obj_set_height(ui_qr_frame, lv_pct(95));
    lv_obj_set_x(ui_qr_frame, -42);
    lv_obj_set_y(ui_qr_frame, 0);
    lv_obj_set_align(ui_qr_frame, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_qr_frame, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_qr_frame, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_qr_frame, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_qr_frame, lv_color_hex(0x161A29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_qr_frame, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_qr_frame, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_qr_frame, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conS6 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_conS6);
    lv_obj_set_width(ui_conS6, lv_pct(100));
    lv_obj_set_height(ui_conS6, lv_pct(100));
    lv_obj_set_align(ui_conS6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_conS6, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_conS6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container12 = lv_obj_create(ui_conS6);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, lv_pct(100));
    lv_obj_set_height(ui_Container12, lv_pct(30));
    lv_obj_set_align(ui_Container12, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btn_reset = lv_btn_create(ui_Container12);
    lv_obj_set_width(ui_btn_reset, lv_pct(15));
    lv_obj_set_height(ui_btn_reset, lv_pct(80));
    lv_obj_set_x(ui_btn_reset, 10);
    lv_obj_set_y(ui_btn_reset, 0);
    lv_obj_set_align(ui_btn_reset, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_btn_reset, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_reset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_reset, &ui_img_asset_95_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_reset, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_reset, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_reset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 0);
    lv_obj_set_y(ui_Label13, -10);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "กรุณารอ เครื่องกำลังทำงาน");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x1B0A78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_Supermarket18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 0);
    lv_obj_set_y(ui_Label10, 10);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Please wait, the machine is working.");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x1B0A78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_Supermarget14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_img_temp = lv_btn_create(ui_Container12);
    lv_obj_set_width(ui_btn_img_temp, 130);
    lv_obj_set_height(ui_btn_img_temp, 70);
    lv_obj_set_x(ui_btn_img_temp, -10);
    lv_obj_set_y(ui_btn_img_temp, 0);
    lv_obj_set_align(ui_btn_img_temp, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_btn_img_temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_img_temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_img_temp, &ui_img_asset_96_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btn_img_temp, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_img_temp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_img_temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container13 = lv_obj_create(ui_conS6);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, lv_pct(100));
    lv_obj_set_height(ui_Container13, lv_pct(37));
    lv_obj_set_x(ui_Container13, 0);
    lv_obj_set_y(ui_Container13, lv_pct(30));
    lv_obj_set_align(ui_Container13, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container13, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_timer_machine = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_lb_timer_machine, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_timer_machine, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lb_timer_machine, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_timer_machine, "00:00:00");
    lv_obj_add_flag(ui_lb_timer_machine, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_lb_timer_machine, lv_color_hex(0x433F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_timer_machine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_timer_machine, &ui_font_Supermarget72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_state_th = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_lb_state_th, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_state_th, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lb_state_th, 0);
    lv_obj_set_y(ui_lb_state_th, -10);
    lv_obj_set_align(ui_lb_state_th, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_state_th, "เครื่องกำลังทำงาน");
    lv_obj_set_style_text_color(ui_lb_state_th, lv_color_hex(0x433F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_state_th, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_state_th, &ui_font_Supermarket48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_state_en = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_lb_state_en, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_state_en, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lb_state_en, 0);
    lv_obj_set_y(ui_lb_state_en, 30);
    lv_obj_set_align(ui_lb_state_en, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_state_en, "Machine is runing");
    lv_obj_set_style_text_color(ui_lb_state_en, lv_color_hex(0x433F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_state_en, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_state_en, &ui_font_Supermarket18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_con_icon_step = lv_obj_create(ui_conS6);
    lv_obj_remove_style_all(ui_con_icon_step);
    lv_obj_set_width(ui_con_icon_step, lv_pct(100));
    lv_obj_set_height(ui_con_icon_step, lv_pct(32));
    lv_obj_set_x(ui_con_icon_step, 0);
    lv_obj_set_y(ui_con_icon_step, 217);
    lv_obj_set_align(ui_con_icon_step, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_con_icon_step, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_wash = lv_img_create(ui_con_icon_step);
    lv_img_set_src(ui_img_wash, &ui_img_asset_77_png);
    lv_obj_set_width(ui_img_wash, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_img_wash, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_img_wash, 70);
    lv_obj_set_y(ui_img_wash, 0);
    lv_obj_set_align(ui_img_wash, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_img_wash, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_wash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_img_wash, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_img_wash, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_img_wash, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_img_wash, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_img_wash, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_rin = lv_img_create(ui_con_icon_step);
    lv_img_set_src(ui_img_rin, &ui_img_asset_78_png);
    lv_obj_set_width(ui_img_rin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_img_rin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_img_rin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_rin, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_rin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_img_rin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_img_rin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_img_rin, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_img_rin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_img_rin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_spin = lv_img_create(ui_con_icon_step);
    lv_img_set_src(ui_img_spin, &ui_img_asset_79_png);
    lv_obj_set_width(ui_img_spin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_img_spin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_img_spin, -70);
    lv_obj_set_y(ui_img_spin, 0);
    lv_obj_set_align(ui_img_spin, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_img_spin, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_spin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_img_spin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_img_spin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_img_spin, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_img_spin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_img_spin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_con_dry_text = lv_obj_create(ui_conS6);
    lv_obj_remove_style_all(ui_con_dry_text);
    lv_obj_set_width(ui_con_dry_text, lv_pct(100));
    lv_obj_set_height(ui_con_dry_text, lv_pct(32));
    lv_obj_set_x(ui_con_dry_text, 0);
    lv_obj_set_y(ui_con_dry_text, 217);
    lv_obj_set_align(ui_con_dry_text, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_con_dry_text, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_con_dry_text, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lb_dry4 = lv_label_create(ui_con_dry_text);
    lv_obj_set_width(ui_lb_dry4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_dry4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lb_dry4, 0);
    lv_obj_set_y(ui_lb_dry4, -10);
    lv_obj_set_align(ui_lb_dry4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_dry4,
                      "สามารถเปิดฝาเครื่อง เพื่อตรวจเช็คผ้า หรือหยอดเหรียญต่อเวลาได้");
    lv_obj_set_style_text_color(ui_lb_dry4, lv_color_hex(0x433F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_dry4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_dry4, &ui_font_Supermarket18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_dry2 = lv_label_create(ui_con_dry_text);
    lv_obj_set_width(ui_lb_dry2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_dry2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lb_dry2, 0);
    lv_obj_set_y(ui_lb_dry2, 10);
    lv_obj_set_align(ui_lb_dry2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lb_dry2,
                      "\"The machine cover can be opened to check the laundry or insert coins for an extended time.\"");
    lv_obj_set_style_text_color(ui_lb_dry2, lv_color_hex(0x433F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_dry2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_dry2, &ui_font_Supermarket10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_tx_pin, ui_event_tx_pin, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard, ui_tx_pin);
    lv_obj_add_event_cb(ui_tx_wifi_name, ui_event_tx_wifi_name, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tx_wifi_pass, ui_event_tx_wifi_pass, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard2, ui_tx_wifi_pass);

}
