SET(SOURCES screens/ui_Screen1.c
    ui.c
    components/ui_comp_hook.c
    ui_helpers.c
    ui_events.c
    images/ui_img_asset_93_png.c
    images/ui_img_asset_83_png.c
    images/ui_img_asset_94_png.c
    images/ui_img_asset_73_png.c
    images/ui_img_asset_72_png.c
    images/ui_img_asset_91_png.c
    images/ui_img_asset_97_png.c
    images/ui_img_asset_98_png.c
    images/ui_img_asset_99_png.c
    images/ui_img_asset_100_png.c
    images/ui_img_asset_101_png.c
    images/ui_img_asset_84_png.c
    images/ui_img_asset_87_png.c
    images/ui_img_asset_89_png.c
    images/ui_img_asset_88_png.c
    images/ui_img_asset_96_png.c
    images/ui_img_asset_86_png.c
    images/ui_img_asset_85_png.c
    images/ui_img_asset_92_png.c
    images/ui_img_asset_95_png.c
    images/ui_img_asset_77_png.c
    images/ui_img_asset_78_png.c
    images/ui_img_asset_79_png.c
    images/ui_img_asset_102_png.c
    images/ui_img_asset_103_png.c
    images/ui_img_asset_104_png.c
    images/ui_img_asset_105_png.c
    images/ui_img_asset_106_png.c
    images/ui_img_asset_107_png.c
    images/ui_img_asset_90_png.c
    fonts/ui_font_Supermarget14.c
    fonts/ui_font_Supermarget72.c
    fonts/ui_font_Supermarket10.c
    fonts/ui_font_Supermarket18.c
    fonts/ui_font_Supermarket48.c)

add_library(ui ${SOURCES})
