// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: melody qr code atd35

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_conS1;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Container3;
lv_obj_t * ui_icon_wifi;
lv_obj_t * ui_icon_mqtt;
lv_obj_t * ui_lb_datetime;
lv_obj_t * ui_btn_wifi_setting;
lv_obj_t * ui_btn_pass;
lv_obj_t * ui_con_login;
lv_obj_t * ui_btn_login;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_con_key;
lv_obj_t * ui_btn_check_key;
lv_obj_t * ui_lb_btn_command;
void ui_event_tx_pin(lv_event_t * e);
lv_obj_t * ui_tx_pin;
lv_obj_t * ui_Keyboard;
lv_obj_t * ui_con_command;
lv_obj_t * ui_Container20;
lv_obj_t * ui_btn_ldr;
lv_obj_t * ui_lb_ldr;
lv_obj_t * ui_btn_slot;
lv_obj_t * ui_lb_slot;
lv_obj_t * ui_btn_mode;
lv_obj_t * ui_lb_mode;
lv_obj_t * ui_btn_command_home;
lv_obj_t * ui_btn_setting;
lv_obj_t * ui_lb_setting;
lv_obj_t * ui_btn_change_pass;
lv_obj_t * ui_lb_change_pass;
lv_obj_t * ui_Container22;
lv_obj_t * ui_btn_power;
lv_obj_t * ui_btn_jok;
lv_obj_t * ui_btn_start;
lv_obj_t * ui_btn_spin;
lv_obj_t * ui_btn_temp;
lv_obj_t * ui_con_program;
lv_obj_t * ui_btn_program1;
lv_obj_t * ui_lb_program1;
lv_obj_t * ui_btn_program2;
lv_obj_t * ui_lb_program2;
lv_obj_t * ui_btn_program3;
lv_obj_t * ui_lb_program3;
lv_obj_t * ui_btn_program5;
lv_obj_t * ui_lb_program5;
lv_obj_t * ui_btn_program6;
lv_obj_t * ui_lb_program6;
lv_obj_t * ui_btn_program4;
lv_obj_t * ui_lb_program4;
lv_obj_t * ui_con_wifi;
lv_obj_t * ui_btn_save_wifi;
lv_obj_t * ui_lb_btn_command2;
void ui_event_tx_wifi_name(lv_event_t * e);
lv_obj_t * ui_tx_wifi_name;
void ui_event_tx_wifi_pass(lv_event_t * e);
lv_obj_t * ui_tx_wifi_pass;
lv_obj_t * ui_Keyboard2;
lv_obj_t * ui_con_all_setting;
lv_obj_t * ui_Container4;
lv_obj_t * ui_lb_display_setting;
lv_obj_t * ui_btn_back;
lv_obj_t * ui_Label12;
lv_obj_t * ui_btn_Reset;
lv_obj_t * ui_Label16;
lv_obj_t * ui_btn_Up;
lv_obj_t * ui_Label19;
lv_obj_t * ui_btn_Down;
lv_obj_t * ui_Label17;
lv_obj_t * ui_btn_Setting;
lv_obj_t * ui_Label20;
lv_obj_t * ui_conS2;
lv_obj_t * ui_Container1;
lv_obj_t * ui_btn_back1;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label3;
lv_obj_t * ui_con_shoot;
lv_obj_t * ui_pn_mode1;
lv_obj_t * ui_price1;
lv_obj_t * ui_Image12;
lv_obj_t * ui_pn_mode3;
lv_obj_t * ui_price3;
lv_obj_t * ui_Image13;
lv_obj_t * ui_pn_mode2;
lv_obj_t * ui_price2;
lv_obj_t * ui_Image11;
lv_obj_t * ui_con_shoot1;
lv_obj_t * ui_pn_dry1;
lv_obj_t * ui_price_dry1;
lv_obj_t * ui_Image7;
lv_obj_t * ui_con_time_dry;
lv_obj_t * ui_lb_timedry1;
lv_obj_t * ui_Label18;
lv_obj_t * ui_pn_dry2;
lv_obj_t * ui_price_dry2;
lv_obj_t * ui_Image8;
lv_obj_t * ui_con_time_dry3;
lv_obj_t * ui_lb_timedry2;
lv_obj_t * ui_Label22;
lv_obj_t * ui_pn_dry3;
lv_obj_t * ui_price_dry3;
lv_obj_t * ui_Image9;
lv_obj_t * ui_con_time_dry2;
lv_obj_t * ui_lb_timedry3;
lv_obj_t * ui_Label15;
lv_obj_t * ui_conS3;
lv_obj_t * ui_Container6;
lv_obj_t * ui_btn_back2;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Container7;
lv_obj_t * ui_pn_qr;
lv_obj_t * ui_Image3;
lv_obj_t * ui_pn_coin;
lv_obj_t * ui_Image2;
lv_obj_t * ui_conS4;
lv_obj_t * ui_Container5;
lv_obj_t * ui_btn_back3;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Container8;
lv_obj_t * ui_lb_coin;
lv_obj_t * ui_Image4;
lv_obj_t * ui_conS5;
lv_obj_t * ui_Container9;
lv_obj_t * ui_btn_back4;
lv_obj_t * ui_lb_clock_qr;
lv_obj_t * ui_Image5;
lv_obj_t * ui_lb_promtpay;
lv_obj_t * ui_Container10;
lv_obj_t * ui_Container11;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label11;
lv_obj_t * ui_lb_price_qr;
lv_obj_t * ui_qr_frame;
lv_obj_t * ui_conS6;
lv_obj_t * ui_Container12;
lv_obj_t * ui_btn_reset;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label10;
lv_obj_t * ui_btn_img_temp;
lv_obj_t * ui_Container13;
lv_obj_t * ui_lb_timer_machine;
lv_obj_t * ui_lb_state_th;
lv_obj_t * ui_lb_state_en;
lv_obj_t * ui_con_icon_step;
lv_obj_t * ui_img_wash;
lv_obj_t * ui_img_rin;
lv_obj_t * ui_img_spin;
lv_obj_t * ui_con_dry_text;
lv_obj_t * ui_lb_dry4;
lv_obj_t * ui_lb_dry2;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_asset_[30] = {&ui_img_asset_100_png, &ui_img_asset_101_png, &ui_img_asset_102_png, &ui_img_asset_103_png, &ui_img_asset_104_png, &ui_img_asset_105_png, &ui_img_asset_106_png, &ui_img_asset_107_png, &ui_img_asset_72_png, &ui_img_asset_73_png, &ui_img_asset_77_png, &ui_img_asset_78_png, &ui_img_asset_79_png, &ui_img_asset_83_png, &ui_img_asset_84_png, &ui_img_asset_85_png, &ui_img_asset_86_png, &ui_img_asset_87_png, &ui_img_asset_88_png, &ui_img_asset_89_png, &ui_img_asset_90_png, &ui_img_asset_91_png, &ui_img_asset_92_png, &ui_img_asset_93_png, &ui_img_asset_94_png, &ui_img_asset_95_png, &ui_img_asset_96_png, &ui_img_asset_97_png, &ui_img_asset_98_png, &ui_img_asset_99_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_tx_pin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard,  ui_tx_pin);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_tx_wifi_name(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_tx_wifi_pass);
    }
}
void ui_event_tx_wifi_pass(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_tx_wifi_pass);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
