// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: melody qr code atd35

#ifndef _MELODY_QR_CODE_ATD35_UI_H
#define _MELODY_QR_CODE_ATD35_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_conS1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_icon_wifi;
extern lv_obj_t * ui_icon_mqtt;
extern lv_obj_t * ui_lb_datetime;
extern lv_obj_t * ui_btn_wifi_setting;
extern lv_obj_t * ui_btn_pass;
extern lv_obj_t * ui_con_login;
extern lv_obj_t * ui_btn_login;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_con_key;
extern lv_obj_t * ui_btn_check_key;
extern lv_obj_t * ui_lb_btn_command;
void ui_event_tx_pin(lv_event_t * e);
extern lv_obj_t * ui_tx_pin;
extern lv_obj_t * ui_Keyboard;
extern lv_obj_t * ui_con_command;
extern lv_obj_t * ui_Container20;
extern lv_obj_t * ui_btn_ldr;
extern lv_obj_t * ui_lb_ldr;
extern lv_obj_t * ui_btn_slot;
extern lv_obj_t * ui_lb_slot;
extern lv_obj_t * ui_btn_mode;
extern lv_obj_t * ui_lb_mode;
extern lv_obj_t * ui_btn_command_home;
extern lv_obj_t * ui_btn_setting;
extern lv_obj_t * ui_lb_setting;
extern lv_obj_t * ui_btn_change_pass;
extern lv_obj_t * ui_lb_change_pass;
extern lv_obj_t * ui_Container22;
extern lv_obj_t * ui_btn_power;
extern lv_obj_t * ui_btn_jok;
extern lv_obj_t * ui_btn_start;
extern lv_obj_t * ui_btn_spin;
extern lv_obj_t * ui_btn_temp;
extern lv_obj_t * ui_con_program;
extern lv_obj_t * ui_btn_program1;
extern lv_obj_t * ui_lb_program1;
extern lv_obj_t * ui_btn_program2;
extern lv_obj_t * ui_lb_program2;
extern lv_obj_t * ui_btn_program3;
extern lv_obj_t * ui_lb_program3;
extern lv_obj_t * ui_btn_program5;
extern lv_obj_t * ui_lb_program5;
extern lv_obj_t * ui_btn_program6;
extern lv_obj_t * ui_lb_program6;
extern lv_obj_t * ui_btn_program4;
extern lv_obj_t * ui_lb_program4;
extern lv_obj_t * ui_con_wifi;
extern lv_obj_t * ui_btn_save_wifi;
extern lv_obj_t * ui_lb_btn_command2;
void ui_event_tx_wifi_name(lv_event_t * e);
extern lv_obj_t * ui_tx_wifi_name;
void ui_event_tx_wifi_pass(lv_event_t * e);
extern lv_obj_t * ui_tx_wifi_pass;
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui_con_all_setting;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_lb_display_setting;
extern lv_obj_t * ui_btn_back;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_btn_Reset;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_btn_Up;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_btn_Down;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_btn_Setting;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_conS2;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_btn_back1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_con_shoot;
extern lv_obj_t * ui_pn_mode1;
extern lv_obj_t * ui_price1;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_pn_mode3;
extern lv_obj_t * ui_price3;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_pn_mode2;
extern lv_obj_t * ui_price2;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_con_shoot1;
extern lv_obj_t * ui_pn_dry1;
extern lv_obj_t * ui_price_dry1;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_con_time_dry;
extern lv_obj_t * ui_lb_timedry1;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_pn_dry2;
extern lv_obj_t * ui_price_dry2;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_con_time_dry3;
extern lv_obj_t * ui_lb_timedry2;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_pn_dry3;
extern lv_obj_t * ui_price_dry3;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_con_time_dry2;
extern lv_obj_t * ui_lb_timedry3;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_conS3;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_btn_back2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_pn_qr;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_pn_coin;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_conS4;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_btn_back3;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_lb_coin;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_conS5;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_btn_back4;
extern lv_obj_t * ui_lb_clock_qr;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_lb_promtpay;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_lb_price_qr;
extern lv_obj_t * ui_qr_frame;
extern lv_obj_t * ui_conS6;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_btn_reset;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_btn_img_temp;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_lb_timer_machine;
extern lv_obj_t * ui_lb_state_th;
extern lv_obj_t * ui_lb_state_en;
extern lv_obj_t * ui_con_icon_step;
extern lv_obj_t * ui_img_wash;
extern lv_obj_t * ui_img_rin;
extern lv_obj_t * ui_img_spin;
extern lv_obj_t * ui_con_dry_text;
extern lv_obj_t * ui_lb_dry4;
extern lv_obj_t * ui_lb_dry2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_asset_93_png);    // assets/Asset 93.png
LV_IMG_DECLARE(ui_img_asset_83_png);    // assets/Asset 83.png
LV_IMG_DECLARE(ui_img_asset_94_png);    // assets/Asset 94.png
LV_IMG_DECLARE(ui_img_asset_73_png);    // assets/Asset 73.png
LV_IMG_DECLARE(ui_img_asset_72_png);    // assets/Asset 72.png
LV_IMG_DECLARE(ui_img_asset_91_png);    // assets/Asset 91.png
LV_IMG_DECLARE(ui_img_asset_97_png);    // assets/Asset 97.png
LV_IMG_DECLARE(ui_img_asset_98_png);    // assets/Asset 98.png
LV_IMG_DECLARE(ui_img_asset_99_png);    // assets/Asset 99.png
LV_IMG_DECLARE(ui_img_asset_100_png);    // assets/Asset 100.png
LV_IMG_DECLARE(ui_img_asset_101_png);    // assets/Asset 101.png
LV_IMG_DECLARE(ui_img_asset_84_png);    // assets/Asset 84.png
LV_IMG_DECLARE(ui_img_asset_87_png);    // assets/Asset 87.png
LV_IMG_DECLARE(ui_img_asset_89_png);    // assets/Asset 89.png
LV_IMG_DECLARE(ui_img_asset_88_png);    // assets/Asset 88.png
LV_IMG_DECLARE(ui_img_asset_96_png);    // assets/Asset 96.png
LV_IMG_DECLARE(ui_img_asset_86_png);    // assets/Asset 86.png
LV_IMG_DECLARE(ui_img_asset_85_png);    // assets/Asset 85.png
LV_IMG_DECLARE(ui_img_asset_92_png);    // assets/Asset 92.png
LV_IMG_DECLARE(ui_img_asset_95_png);    // assets/Asset 95.png
LV_IMG_DECLARE(ui_img_asset_77_png);    // assets/Asset 77.png
LV_IMG_DECLARE(ui_img_asset_78_png);    // assets/Asset 78.png
LV_IMG_DECLARE(ui_img_asset_79_png);    // assets/Asset 79.png
LV_IMG_DECLARE(ui_img_asset_102_png);    // assets/Asset 102.png
LV_IMG_DECLARE(ui_img_asset_103_png);    // assets/Asset 103.png
LV_IMG_DECLARE(ui_img_asset_104_png);    // assets/Asset 104.png
LV_IMG_DECLARE(ui_img_asset_105_png);    // assets/Asset 105.png
LV_IMG_DECLARE(ui_img_asset_106_png);    // assets/Asset 106.png
LV_IMG_DECLARE(ui_img_asset_107_png);    // assets/Asset 107.png
LV_IMG_DECLARE(ui_img_asset_90_png);    // assets/Asset 90.png



LV_FONT_DECLARE(ui_font_Supermarget14);
LV_FONT_DECLARE(ui_font_Supermarget72);
LV_FONT_DECLARE(ui_font_Supermarket10);
LV_FONT_DECLARE(ui_font_Supermarket18);
LV_FONT_DECLARE(ui_font_Supermarket48);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
